import type { ClassData, Student } from "./types";

export const SUPER_ADMIN_EMAILS = ["shibbir.ahma.2025@gmail.com"];

export const MARKSHEET_TRANSLATIONS = {
  bn: {
    title: "মাদরাসা ফলাফল পত্র",
    academicYear: "শিক্ষাবর্ষ",
    studentName: "শিক্ষার্থীর নাম",
    class: "শ্রেণি",
    roll: "রোল নম্বর",
    fatherName: "পিতার নাম",
    rank: "র‍্যাঙ্ক",
    result: "ফলাফল",
    subject: "বিষয়",
    fullMarks: "পূর্ণমান",
    passMarks: "পাস নম্বর",
    obtainedMarks: "প্রাপ্ত নম্বর",
    total: "সর্বমোট",
    percentage: "শতকরা",
    grade: "গ্রেড",
    teacherSignature: "শ্রেণি শিক্ষকের স্বাক্ষর",
    principalSignature: "অধ্যক্ষের স্বাক্ষর",
    historyTitle: "শিক্ষার্থীর একাডেমিক ইতিহাস",
    exam: "পরীক্ষা",
    viewMarksheet: "মার্কশিট দেখুন",
    loading: "লোড হচ্ছে...",
    select: "নির্বাচন করুন",
    academicYearLabel: "শিক্ষাবর্ষ",
    classLabel: "শ্রেণি",
    examLabel: "পরীক্ষা",
    studentLabel: "শিক্ষার্থী",
    print: "প্রিন্ট",
    share: "শেয়ার",
    save: "সংরক্ষণ করুন",
    edit: "সম্পাদনা",
    cancel: "বাতিল",
    pass: "কৃতকার্য",
    fail: "অকৃতকার্য"
  },
  en: {
    title: "Madrasa Result Sheet",
    academicYear: "Academic Year",
    studentName: "Student Name",
    class: "Class",
    roll: "Roll No",
    fatherName: "Father's Name",
    rank: "Rank",
    result: "Result",
    subject: "Subject",
    fullMarks: "Full Marks",
    passMarks: "Pass Marks",
    obtainedMarks: "Obtained Marks",
    total: "Total",
    percentage: "Percentage",
    grade: "Grade",
    teacherSignature: "Class Teacher's Signature",
    principalSignature: "Principal's Signature",
    historyTitle: "Student Academic History",
    exam: "Exam",
    viewMarksheet: "View Marksheet",
    loading: "Loading...",
    select: "Select",
    academicYearLabel: "Academic Year",
    classLabel: "Class",
    examLabel: "Exam",
    studentLabel: "Student",
    print: "Print",
    share: "Share",
    save: "Save",
    edit: "Edit",
    cancel: "Cancel",
    pass: "Pass",
    fail: "Fail"
  },
  ar: {
    title: "كشف درجات المدرسة",
    academicYear: "السنة الدراسية",
    studentName: "اسم الطالب",
    class: "الفصل",
    roll: "رقم الجلوس",
    fatherName: "اسم الأب",
    rank: "الرتبة",
    result: "النتيجة",
    subject: "المادة",
    fullMarks: "الدرجة الكاملة",
    passMarks: "درجة النجاح",
    obtainedMarks: "الدرجة الحاصل عليها",
    total: "المجموع",
    percentage: "النسبة المئوية",
    grade: "التقدير",
    teacherSignature: "توقيع معلم الفصل",
    principalSignature: "توقيع المدير",
    historyTitle: "السجل الأكاديمي للطالب",
    exam: "الامتحان",
    viewMarksheet: "عرض كشف الدرجات",
    loading: "جاري التحميل...",
    select: "اختر",
    academicYearLabel: "السنة الدراسية",
    classLabel: "الفصل",
    examLabel: "الامتحان",
    studentLabel: "الطالب",
    print: "طباعة",
    share: "مشاركة",
    save: "حفظ",
    edit: "تعديل",
    cancel: "إلغاء",
    pass: "ناجح",
    fail: "راسب"
  }
};

export const CLASSES: ClassData[] = [
  { id: "class-1", name: "Class 1" },
  { id: "class-2", name: "Class 2" },
  { id: "class-3", name: "Class 3" },
  { id: "class-4", name: "Class 4" },
  { id: "class-5", name: "Class 5" },
  { id: "class-6", name: "Class 6" },
  { id: "class-7", name: "Class 7" },
  { id: "class-8", name: "Class 8" },
  { id: "class-9", name: "Class 9" },
  { id: "class-10", name: "Class 10" },
];

const studentNames = [
  "Abir Ahmed",
  "Jannatul Ferdous",
  "Md. Abdullah",
  "Sumaiya Akter",
  "Imran Hossain",
  "Fatima Khatun",
  "Rakibul Islam",
  "Ayesha Siddiqa",
  "Mehedi Hasan",
  "Nusrat Jahan",
  "Shakib Khan",
  "Sharmin Sultana",
  "Tanvir Rahman",
  "Israt Jahan",
  "Alamgir Hossain",
  "Sabina Yasmin",
  "Zahid Hasan",
  "Roksana Parvin",
  "Kamrul Islam",
  "Mumtaz Begum",
  "Nasir Uddin",
  "Shahnaz Parvin",
  "Firoz Alam",
  "Taslima Akter",
  "Saiful Islam",
  "Afsana Mimi",
  "Jamal Uddin",
  "Dilara Begum",
  "Monir Hossain",
  "Parvin Sultana",
];

const generateStudents = (classId: string, count: number): Student[] => {
  const students: Student[] = [];
  for (let i = 0; i < count; i++) {
    students.push({
      id: `${classId}-student-${i + 1}`,
      classId,
      roll: i + 1,
      name: studentNames[i % studentNames.length],
    });
  }
  return students;
};

export const STUDENTS: { [key: string]: Student[] } = {
  "class-1": generateStudents("class-1", 20),
  "class-2": generateStudents("class-2", 22),
  "class-3": generateStudents("class-3", 25),
  "class-4": generateStudents("class-4", 23),
  "class-5": generateStudents("class-5", 28),
  "class-6": generateStudents("class-6", 30),
  "class-7": generateStudents("class-7", 29),
  "class-8": generateStudents("class-8", 26),
  "class-9": generateStudents("class-9", 27),
  "class-10": generateStudents("class-10", 24),
};
